namespace UnturnedBlackout.Enums;

public enum EAnimationType
{
    LEVEL_UP,
    GUN_LEVEL_UP,
    QUEST_COMPLETION,
    ACHIEVEMENT_COMPLETION,
    BATTLEPASS_TIER_COMPLETION,
    ITEM_UNLOCK,
    KILLSTREAK_AVAILABLE
}