namespace UnturnedBlackout.Enums;

public enum ELoadoutPage
{
    PRIMARY,
    PRIMARY_SKIN,
    SECONDARY,
    SECONDARY_SKIN,
    ATTACHMENT_PRIMARY_SIGHTS,
    ATTACHMENT_PRIMARY_GRIP,
    ATTACHMENT_PRIMARY_CHARM,
    ATTACHMENT_PRIMARY_BARREL,
    ATTACHMENT_PRIMARY_MAGAZINE,
    ATTACHMENT_SECONDARY_SIGHTS,
    ATTACHMENT_SECONDARY_CHARM,
    ATTACHMENT_SECONDARY_BARREL,
    ATTACHMENT_SECONDARY_MAGAZINE,
    KNIFE,
    PERK1,
    PERK2,
    PERK3,
    KILLSTREAK,
    GLOVE,
    CARD,
    TACTICAL,
    LETHAL
}